### ISSUE TITLE
请问您搭建博客，在部署到服务器之前有对项目进行构建打包吗？还是说您直接将项目部署到服务器上，就可以了吗？

### ISSUE THREAD

**Issue by OwnGhy** [scottjeremy/EJblog#1]

**Comment by scottjeremy** [comment]
不用进行打包，直接放在服务器上面就可以了。如果要放到服务器上需要自己再写一个nginx的反向代理才可以正常运行。

**Comment by OwnGhy** [comment]
好的，谢谢指点，我去试试

**Comment by wuyushuooo** [comment]
这个项目可以前后端分离吗？

**Comment by scottjeremy** [comment]
这个项目就是前后端分离的，虽然都是用ejs文件，但我用get请求那些views/xxx.ejs都只是渲染，没有添加数据。页面渲染的数据都是前端ajax调用接口获得的
